version: '3.5'
services:
  discovery:
    image: piomin/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: piomin/gateway-service
    container_name: service-gateway
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  zipkin-service:
    image: piomin/zipkin-service
    container_name: zipkin-service
    build:
      context: ./zipkin-service
      dockerfile: Dockerfile
    ports:
      - "9411:9411"

  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: soa
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      command: --default-authentication-plugin=mysql_native_password
    links:
      - discovery

  chainsaw-store-service:
    image: piomin/chainsaw-store-service
    container_name: chainsaw-store-service
    build:
      context: ./chainsaw-store-service
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      "spring.datasource.url": "jdbc:mysql://database:3306/soa"
    links:
      - discovery
      - database
    depends_on:
      - database

  order-service:
    image: piomin/order-service
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      "spring.datasource.url": "jdbc:mysql://database:3306/soa"
    links:
      - discovery
      - database
    depends_on:
      - database

